#imports:
#    - { resource: 'services/breadcrumb.yml' }
#    - { resource: 'services/datagrid.yml' }
#    - { resource: 'services/dataset.yml' }
#    - { resource: 'services/form.yml' }

services:

    request.helper:
        class: Application\CoreBundle\Helper\Request\RequestHelper
        arguments: ['@request_stack']

    validator.helper:
        class: Application\CoreBundle\Helper\Validator\ValidatorHelper
        arguments: ['@validator']

    translator.helper:
        class: Application\CoreBundle\Helper\Translator\TranslatorHelper
        arguments: ['@translator']

    security.helper:
        class: Application\CoreBundle\Helper\Security\SecurityHelper
        arguments: ['@security.token_storage', '@request.helper', '@security.authorization_checker']

    app.listener.decorating_deserialize:
        class: 'Application\CoreBundle\EventListener\DeserializeListener'
        arguments: ['@api_platform.serializer', '@api_platform.serializer.context_builder', '@api_platform.listener.request.deserialize']
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.request', method: 'onKernelRequest', priority: 2 }

    app.operation_path_resolver.no_separators:
        class: Application\CoreBundle\PathResolver\NoSeparatorsOperationPathResolver
        public: false


