Application\AutoBundle\Entity\AutoSubCategoryHasCarProducer:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\AutoSubCategoryHasCarProducerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        subcategory:
            targetEntity: Application\AutoBundle\Entity\AutoSubCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subcategory_id:
                    referencedColumnName: id
            orphanRemoval: false
        producers:
            targetEntity: Application\AutoBundle\Entity\CarProducer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                producers_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
