Application\AutoBundle\Entity\Car:
    type: entity
    table: car
    repositoryClass: Application\AutoBundle\Repository\CarRepository
    indexes:
        fk_cars_title_idx:
            columns:
                - title
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fuel:
            type: string
            length: 255
            nullable: true
        mileage:
            type: float
            nullable: true
        engineCapacity:
            type: float
            nullable: true
        vehicleType:
            type: string
            length: 255
            nullable: true
        carCondition:
            type: string
            length: 255
            nullable: true
        seatsNumber:
            type: integer
            nullable: true
        transmission:
            type: string
            length: 255
            nullable: true
        exteriorColour:
            type: string
            length: 255
            nullable: true
        airConditioning:
            type: boolean
            nullable: true
    manyToOne:
        models:
            targetEntity: Application\AutoBundle\Entity\Model
            cascade: {  }
            mappedBy:
            inversedBy: cars
            joinColumns:
                model_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
