Application\AutoBundle\Entity\Car:
    type: entity
    table: car
    repositoryClass: Application\AutoBundle\Repository\CarRepository
    indexes:
        fk_cars_title_idx:
            columns:
                - title
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fuel:
            type: string
            length: 255
            nullable: true
        mileage:
            type: integer
            nullable: true
        engineCapacity:
            type: integer
            nullable: true
        vehicleType:
            type: string
            length: 255
            nullable: true
        carCondition:
            type: string
            length: 255
            nullable: true
        seatsNumber:
            type: integer
            nullable: true
        transmission:
            type: string
            length: 255
            nullable: true
        exteriorColour:
            type: string
            length: 255
            nullable: true
        airConditioning:
            type: boolean
            nullable: true
        dateUpdated:
            type: datetime
            nullable: true
            comment: ''
            column: date_updated
        dateCreated:
            type: datetime
            nullable: true
            comment: ''
            column: date_created
    manyToOne:
        models:
            targetEntity: Application\AutoBundle\Entity\Model
            cascade: {  }
            mappedBy:
            inversedBy:
            joinColumns:
                model_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks:
        prePersist: [prePersist]
        preUpdate: [preUpdate]
