Application\AutoBundle\Entity\Car:
    type: entity
    table: cars
    repositoryClass: Application\AutoBundle\Repository\CarRepository
    indexes:
        fk_cars_title_idx:
            columns:
                - title
    fields:
        fuel:
            type: string
            length: 255
            nullable: true
        mileage:
            type: float
            nullable: true
        engineCapacity:
            type: float
            nullable: true
        vehicleType:
            type: string
            length: 255
            nullable: true
        carCondition:
            type: string
            length: 255
            nullable: true
        seatsNumber:
            type: integer
            nullable: true
        transmission:
            type: string
            length: 255
            nullable: true
        exteriorColour:
            type: string
            length: 255
            nullable: true
        airConditioning:
            type: boolean
            nullable: true
    manyToOne:
        models:
            targetEntity: Application\AutoBundle\Entity\CarModel
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cars_id:
                    referencedColumnName: id
            inverseJoinColumns:
                models_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
