Application\AutoBundle\Entity\CarModelHasCar:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\CarModelHasCarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        models:
            targetEntity: Application\AutoBundle\Entity\CarModel
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                models_id:
                    referencedColumnName: id
            orphanRemoval: false
        cars:
            targetEntity: Application\AutoBundle\Entity\Car
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                cars_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
