Application\AutoBundle\Entity\CarProducerHasCarModel:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\CarProducerHasCarModelRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        producers:
            targetEntity: Application\AutoBundle\Entity\CarProducer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                producers_id:
                    referencedColumnName: id
            orphanRemoval: false
        models:
            targetEntity: Application\AutoBundle\Entity\CarModel
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                models_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
