Application\AutoBundle\Entity\CategoryHasAutoSubcategory:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\CategoryHasAutoSubcategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        categories:
            targetEntity: Application\CategoryBundle\Entity\Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
        subcategories:
            targetEntity: Application\AutoBundle\Entity\AutoSubCategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                subcategory_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
