Application\AutoBundle\Entity\ModelHasCars:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\ModelHasCarsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        models:
            targetEntity: Model
            cascade: {  }
            mappedBy:
            inversedBy: null
            joinColumns:
                model_id:
                    referencedColumnName: id
            orphanRemoval: false
        cars:
            targetEntity: Car
            cascade: {  }
            mappedBy:
            inversedBy: null
            joinColumns:
                car_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
