Application\AutoBundle\Entity\ProducerHasModels:
    type: entity
    table: null
    repositoryClass: Application\AutoBundle\Repository\ProducerHasModelsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
    manyToOne:
        producers:
            targetEntity: Application\AutoBundle\Entity\Producer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                producer_id:
                    referencedColumnName: id
            orphanRemoval: false
        models:
            targetEntity: Car
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                model_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
