get_car:
    path: '/car/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Default:getCar'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_item_operation_name: 'getCar'

update_car:
    path: '/user/car/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Default:edit'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_item_operation_name: 'updateCar'

add_car:
    path: '/user/car/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Default:add'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_collection_operation_name: 'addCar'

get_cars:
    path: '/cars/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Default:getCars'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_collection_operation_name: 'getCars'