# CAR
get_car:
    path: '/car/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Car:getCar'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_item_operation_name: 'getCar'

update_car:
    path: '/user/car/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Car:edit'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_item_operation_name: 'updateCar'

add_car:
    path: '/user/car/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Car:add'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_collection_operation_name: 'addCar'

get_cars:
    path: '/cars/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Car:getCars'
        _api_resource_class: 'Application\AutoBundle\Entity\Car'
        _api_collection_operation_name: 'getCars'


# CAR MODEL
get_model:
    path: '/carmodel/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Model:getModel'
        _api_resource_class: 'Application\AutoBundle\Entity\Model'
        _api_item_operation_name: 'getCar'

update_model:
    path: '/user/carmodel/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Model:edit'
        _api_resource_class: 'Application\AutoBundle\Entity\Model'
        _api_item_operation_name: 'updateModel'

add_model:
    path: '/user/carmodel/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Model:add'
        _api_resource_class: 'Application\AutoBundle\Entity\Model'
        _api_collection_operation_name: 'addModel'

get_models:
    path: '/carmodels/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Model:getModels'
        _api_resource_class: 'Application\AutoBundle\Entity\Model'
        _api_collection_operation_name: 'getModels'

# CAR MODEL PRODUCERS
get_car_producer:
    path: '/carproducer/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Producer:getProducer'
        _api_resource_class: 'Application\AutoBundle\Entity\Producer'
        _api_item_operation_name: 'getCarProducer'

update_car_producer:
    path: '/user/carproducer/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Producer:edit'
        _api_resource_class: 'Application\AutoBundle\Entity\Producer'
        _api_item_operation_name: 'updateCarProducer'

add_car_producer:
    path: '/user/carproducer/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationAutoBundle:Admin/Producer:add'
        _api_resource_class: 'Application\AutoBundle\Entity\Producer'
        _api_collection_operation_name: 'addCarProducer'

get_car_producers:
    path: '/carproducers/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationAutoBundle:Front/Producer:getProducers'
        _api_resource_class: 'Application\AutoBundle\Entity\Producer'
        _api_collection_operation_name: 'getCarProducers'