
services:
    doctrine.class_metadata.enhancer_collection:
        class: Application\DoctrineBundle\Enhancer\ClassMetadata\ClassMetadataEnhancerCollection
    doctrine.class_metadata.enhancer_traverser:
        class: Application\DoctrineBundle\Enhancer\ClassMetadata\ClassMetadataEnhancerTraverser
        arguments: ['@doctrine.class_metadata.enhancer_collection']
    doctrine.trait_generator.enhancer_collection:
        class: Application\DoctrineBundle\Enhancer\TraitGenerator\TraitGeneratorEnhancerCollection
    doctrine.trait_generator.enhancer_traverser:
        class: Application\DoctrineBundle\Enhancer\TraitGenerator\TraitGeneratorEnhancerTraverser
        arguments: ['@doctrine.trait_generator.enhancer_collection']
    doctrine.class_metadata.event_subscriber:
        class: Application\DoctrineBundle\EventListener\ClassMetadataEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@doctrine.class_metadata.enhancer_traverser']
    doctrine.timestampable.event_subscriber:
        class: Application\DoctrineBundle\EventListener\TimestampableSubscriber
        tags:
            - { name: doctrine.event_subscriber }
    doctrine.cache_invalidator.event_subscriber:
        class: Application\DoctrineBundle\EventListener\CacheInvalidatorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ['@cache']
    doctrine.command.generate_entity_extra:
        class: Application\DoctrineBundle\Command\GenerateEntityExtraCommand
        tags:
            - { name: console.command }
        arguments: ['@doctrine.trait_generator.enhancer_collection', '@doctrine.trait_generator.enhancer_traverser', '@environment_helper']
    doctrine.helper:
        class: Application\DoctrineBundle\Helper\Doctrine\DoctrineHelper
        arguments: ['@doctrine']
