profile:
    path: '/secured/profile/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationAdminBundle:Security:getProfile'
        _api_resource_class: 'Application\AdminBundle\Entity\User'
        _api_item_operation_name: 'profile'