imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        mapping_types:
            enum:       string
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        metadata_cache_driver:
            type: redis
            host: localhost
            port: 6389
        query_cache_driver:
            type: redis
            host: localhost
            port: 6389
# Swiftmailer Configuration
swiftmailer:
    disable_delivery:  false
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:      "%mailer_port%"
    encryption: "%mailer_encryption%"
    spool:     { type: memory }

# Nelmio CORS
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['X-WSSE', 'Content-Type', 'Accept-Encoding', 'Cache-Control', 'X-Requested-With', 'DNT']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600
#NELMIO API DOC
nelmio_api_doc:
    name:                 "Application"
    exclude_sections:     []
    request_listener:
        enabled:              true
        parameter:            _doc
    sandbox:
        enabled:              true
        endpoint:             null
        accept_type:          null
        body_format:
            formats: []
            default_format: form
        request_format:
            formats: []
            method: accept_header
    swagger:
        api_base_path:        /api
        swagger_version:      '1.2'
        api_version:          '0.1'
        info:
            title:                "Application"
            description:          "Application"
            TermsOfServiceUrl:    null
            contact:              null
            license:              null
            licenseUrl:           null
    cache:
        enabled:              true
        file:                 '%kernel.cache_dir%/api-doc.cache'

api_platform:
    #enable custom path resolver for the entities
    default_operation_path_resolver: 'app.operation_path_resolver.no_separators'
    #TRUE: adds entities to apidoc and controller defined apidoc
    #FALSE: adds only controller defined apidoc
    enable_nelmio_api_doc: true

#DATABASE VERSIONING
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

cache_adapter:
  providers:
    my_redis:
      factory: 'cache.factory.redis'
      options:
        host: 127.0.0.1 # Using custom host
        port: 6389
    my_chain:
      factory: 'cache.factory.chain'
      options:
        services:
            - '@cache.provider.my_redis'