api:
    resource: '.'
    type:     'api_platform'

admin:
    resource: "@ApplicationAdminBundle/Action/"
    prefix:   'annotation'

client:
    resource: "@ApplicationClientBundle/Action/"
    prefix:   'annotation'
