application_customer:
    resource: "@ApplicationCustomerBundle/Resources/config/routing.yml"
    prefix:   /

application_category:
    resource: "@ApplicationCategoryBundle/Resources/config/routing.yml"
    prefix:   /

application_product:
    resource: "@ApplicationProductBundle/Resources/config/routing.yml"
    prefix:   /

application_email:
    resource: "@ApplicationEmailBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: '.'
    type:     'api_platform'

application_app:
    resource: "@ApplicationAppBundle/Resources/config/routing.yml"
    prefix:   /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/
