security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_MEINEKE: ROLE_MEINEKE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory:
                users:
                    apidoc: { password: $2a$12$77DgS/ul7u4nEC1./69ZP.CwyQ5uCzFPMMuy.m19yIgDb.u0WMe2G }

    firewalls:
        wsse_secured:
            pattern: ^/api/secured/.*
            stateless: true
            wsse: true
        secured_area:
            pattern: ^/api/doc/
            http_basic:
                realm: 'API Documentation'
                provider: in_memory
