security:
    encoders:
        Application\AdminBundle\Entity\User: sha512
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_MEINEKE: ROLE_MEINEKE

    providers:
        wsse_provider:
            entity:
                class: Application\AdminBundle\Entity\User  # This class must implement UserProviderIterface
        in_memory:
            memory:
                users:
                    apidoc: { password: $2a$12$77DgS/ul7u4nEC1./69ZP.CwyQ5uCzFPMMuy.m19yIgDb.u0WMe2G }

    firewalls:
        wsse_secured:
            pattern: ^/api/secured/.*
            stateless: true
            wsse: true
