get_customer:
    path: '/customer/{id}/'
    methods:  ['GET']
    defaults:
        _controller: 'ApplicationCustomerBundle:Admin/Customer:getCustomer'
        _api_resource_class: 'Application\CustomerBundle\Entity\Customer'
        _api_item_operation_name: 'getCustomer'

update_customer:
    path: '/customer/{id}/'
    methods:  ['PUT']
    defaults:
        _controller: 'ApplicationCustomerBundle:Admin/Customer:updateCustomer'
        _api_resource_class: 'Application\CustomerBundle\Entity\Customer'
        _api_item_operation_name: 'updateCustomer'

add_customer:
    path: '/customers/'
    methods:  ['POST']
    defaults:
        _controller: 'ApplicationCustomerBundle:Admin/Customer:addCustomer'
        _api_resource_class: 'Application\CustomerBundle\Entity\Customer'
        _api_collection_operation_name: 'addCustomer'

get_customers:
    path: '/customers/'
    methods:  ['get']
    defaults:
        _controller: 'ApplicationCustomerBundle:Admin/Customer:getCustomers'
        _api_resource_class: 'Application\CustomerBundle\Entity\Customer'
        _api_collection_operation_name: 'getCustomers'