Application\CustomerBundle\Entity\CustomerGroup:
    type: entity
    table: customer_group
    id:
        id:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
        roles:
            type: array
            comment: ''
    manyToMany:
        users:
            targetEntity: Customer
            mappedBy: groups
    lifecycleCallbacks: { }
