Application\AutoBundle\Entity\Car:
    properties:
        fuel:
            - NotNull: ~
            - NotBlank: ~
        mileage:
            - NotNull: ~
            - NotNull: ~
        engineCapacity:
            - NotNull: ~
            - NotNull: ~
        engineCapacity:
            - NotNull: ~
            - NotNull: ~
        vehicleType:
            - NotNull: ~
            - NotNull: ~
        carCondition:
            - NotNull: ~
            - NotNull: ~
        seatsNumber:
            - NotNull: ~
            - NotNull: ~
        transmission:
            - NotNull: ~
            - NotNull: ~
        exteriorColour:
            - NotNull: ~
            - NotNull: ~
        airConditioning:
            - NotNull: ~
            - NotNull: ~
