Application\AutoBundle\Entity\Car:
    properties:
        fuel:
            - NotNull: ~
            - NotBlank: ~
        mileage:
            - NotNull: ~
            - NotBlank: ~
            - Type:
                type: float
        engineCapacity:
            - NotNull: ~
            - NotBlank: ~
            - Type:
                type: integer
        vehicleType:
            - NotNull: ~
            - NotBlank: ~
        carCondition:
            - NotNull: ~
            - NotBlank: ~
        seatsNumber:
            - NotNull: ~
            - NotBlank: ~
            - Type:
                type: integer
        transmission:
            - NotNull: ~
            - NotBlank: ~
        exteriorColour:
            - NotNull: ~
            - NotBlank: ~
        airConditioning:
            - NotNull: ~
            - NotBlank: ~