parameters:
    admin.registration.confirmation.template: ApplicationEmailBundle:Registration:email.txt.twig

services:
    email.user_confirmation:
        class: Application\EmailBundle\Mailer\Mailer
        arguments: ["@mailer", "@router", "@templating", {"confirmation.template": %admin.registration.confirmation.template% }]
