<?php

namespace Application\AutoBundle\Repository;

/**
 * AutoSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
