<?php

namespace Application\AutoBundle\Repository;

/**
 * AutoSubCategoryHasCarProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoSubCategoryHasCarProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
