<?php

namespace Application\AutoBundle\Repository;

/**
 * AutoSubCategoryHasProducersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoSubCategoryHasProducersRepository extends \Doctrine\ORM\EntityRepository
{
}
