<?php

namespace Application\AutoBundle\Repository;

/**
 * CarHasProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarHasProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
