<?php

namespace Application\AutoBundle\Repository;

/**
 * CarModelHasCarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarModelHasCarRepository extends \Doctrine\ORM\EntityRepository
{
}
