<?php

namespace Application\AutoBundle\Repository;

/**
 * CarProducerHasCarModelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarProducerHasCarModelRepository extends \Doctrine\ORM\EntityRepository
{
}
