<?php

namespace Application\AutoBundle\Repository;

/**
 * CarProducerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarProducerRepository extends \Doctrine\ORM\EntityRepository
{
}
