<?php

namespace Application\AutoBundle\Repository;

/**
 * CategoryHasAutoSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryHasAutoSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
