<?php

namespace Application\AutoBundle\Repository;

/**
 * CategoryHasAutoSubcategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryHasAutoSubcategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
