<?php

namespace Application\AutoBundle\Repository;

/**
 * ModelHasCarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelHasCarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModelCars($id) {

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('modelHasCars', 'cars', 'models');
        $qb->from('ApplicationAutoBundle:ModelHasCars', 'modelHasCars');
        $qb->leftJoin('ApplicationAutoBundle:Model', 'models', 'WITH', 'models.id = modelHasCars.models');
        $qb->leftJoin('ApplicationAutoBundle:Car', 'cars', 'WITH', 'cars.id = modelHasCars.cars');
        $qb->where('models.id = :id');
        $qb->setParameter('id', $id);
        $qb->groupBy('modelHasCars.models');

        return $qb->getQuery()->getResult();

    }
}
