<?php

namespace Application\AutoBundle\Repository;

/**
 * ModelHasCarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelHasCarsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getModelCars($id) {

        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('model, cars');
        $qb->from('ApplicationAutoBundle:Model', 'model');
        $qb->leftJoin('ApplicationAutoBundle:ModelHasCars', 'modelHasCars', 'WITH', 'model.id = modelHasCars.models');
        $qb->leftJoin('ApplicationAutoBundle:Car', 'cars', 'WITH', 'cars.id = modelHasCars.cars');
        $qb->where('model.id = :id');
        $qb->setParameter('id', $id);
       // $qb->groupBy('modelHasCars.models');

        return $qb->getQuery()->getResult();

    }
}
