<?php

namespace Application\AutoBundle\Repository;

/**
 * ProducerHasModelsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducerHasModelsRepository extends \Doctrine\ORM\EntityRepository
{
}
